//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/thePlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ThePlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ThePlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""thePlayerControls"",
    ""maps"": [
        {
            ""name"": ""thePlayer"",
            ""id"": ""6d4f50f5-b796-4ee3-bd05-c8ca4c0da22c"",
            ""actions"": [
                {
                    ""name"": ""CursorMoves"",
                    ""type"": ""Value"",
                    ""id"": ""25fd35d9-9055-40cc-88ec-164333912624"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftAbilitySwitch"",
                    ""type"": ""Button"",
                    ""id"": ""f38b71f0-1d64-4da2-829e-03a9f48e6cd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightAbilitySwitch"",
                    ""type"": ""Button"",
                    ""id"": ""50a69ed2-81df-4315-95be-28972a2d5e01"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorMovesTwo"",
                    ""type"": ""Value"",
                    ""id"": ""c76ca78a-4897-4e22-bf6a-cbee60b41b83"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f2b0fe48-89be-48df-a664-99dac7dcb0b3"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ExternalController"",
                    ""action"": ""CursorMoves"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b47d4f18-7066-4a5e-87b8-713d8fb57daf"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseController"",
                    ""action"": ""leftAbilitySwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92363269-036d-4af5-a138-286113d7a9b5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ExternalController"",
                    ""action"": ""leftAbilitySwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb7125c2-3fd8-4629-b724-9336542f2d32"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseController"",
                    ""action"": ""rightAbilitySwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""112afc62-c92a-481a-b4e4-0bbfa83dc9d8"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""ExternalController"",
                    ""action"": ""rightAbilitySwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""273fe10f-bcd1-4b21-a8e7-24a30e6a3ab7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MouseController"",
                    ""action"": ""CursorMovesTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""ExternalController"",
            ""bindingGroup"": ""ExternalController"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""MouseController"",
            ""bindingGroup"": ""MouseController"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // thePlayer
        m_thePlayer = asset.FindActionMap("thePlayer", throwIfNotFound: true);
        m_thePlayer_CursorMoves = m_thePlayer.FindAction("CursorMoves", throwIfNotFound: true);
        m_thePlayer_leftAbilitySwitch = m_thePlayer.FindAction("leftAbilitySwitch", throwIfNotFound: true);
        m_thePlayer_rightAbilitySwitch = m_thePlayer.FindAction("rightAbilitySwitch", throwIfNotFound: true);
        m_thePlayer_CursorMovesTwo = m_thePlayer.FindAction("CursorMovesTwo", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // thePlayer
    private readonly InputActionMap m_thePlayer;
    private List<IThePlayerActions> m_ThePlayerActionsCallbackInterfaces = new List<IThePlayerActions>();
    private readonly InputAction m_thePlayer_CursorMoves;
    private readonly InputAction m_thePlayer_leftAbilitySwitch;
    private readonly InputAction m_thePlayer_rightAbilitySwitch;
    private readonly InputAction m_thePlayer_CursorMovesTwo;
    public struct ThePlayerActions
    {
        private @ThePlayerControls m_Wrapper;
        public ThePlayerActions(@ThePlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CursorMoves => m_Wrapper.m_thePlayer_CursorMoves;
        public InputAction @leftAbilitySwitch => m_Wrapper.m_thePlayer_leftAbilitySwitch;
        public InputAction @rightAbilitySwitch => m_Wrapper.m_thePlayer_rightAbilitySwitch;
        public InputAction @CursorMovesTwo => m_Wrapper.m_thePlayer_CursorMovesTwo;
        public InputActionMap Get() { return m_Wrapper.m_thePlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ThePlayerActions set) { return set.Get(); }
        public void AddCallbacks(IThePlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_ThePlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ThePlayerActionsCallbackInterfaces.Add(instance);
            @CursorMoves.started += instance.OnCursorMoves;
            @CursorMoves.performed += instance.OnCursorMoves;
            @CursorMoves.canceled += instance.OnCursorMoves;
            @leftAbilitySwitch.started += instance.OnLeftAbilitySwitch;
            @leftAbilitySwitch.performed += instance.OnLeftAbilitySwitch;
            @leftAbilitySwitch.canceled += instance.OnLeftAbilitySwitch;
            @rightAbilitySwitch.started += instance.OnRightAbilitySwitch;
            @rightAbilitySwitch.performed += instance.OnRightAbilitySwitch;
            @rightAbilitySwitch.canceled += instance.OnRightAbilitySwitch;
            @CursorMovesTwo.started += instance.OnCursorMovesTwo;
            @CursorMovesTwo.performed += instance.OnCursorMovesTwo;
            @CursorMovesTwo.canceled += instance.OnCursorMovesTwo;
        }

        private void UnregisterCallbacks(IThePlayerActions instance)
        {
            @CursorMoves.started -= instance.OnCursorMoves;
            @CursorMoves.performed -= instance.OnCursorMoves;
            @CursorMoves.canceled -= instance.OnCursorMoves;
            @leftAbilitySwitch.started -= instance.OnLeftAbilitySwitch;
            @leftAbilitySwitch.performed -= instance.OnLeftAbilitySwitch;
            @leftAbilitySwitch.canceled -= instance.OnLeftAbilitySwitch;
            @rightAbilitySwitch.started -= instance.OnRightAbilitySwitch;
            @rightAbilitySwitch.performed -= instance.OnRightAbilitySwitch;
            @rightAbilitySwitch.canceled -= instance.OnRightAbilitySwitch;
            @CursorMovesTwo.started -= instance.OnCursorMovesTwo;
            @CursorMovesTwo.performed -= instance.OnCursorMovesTwo;
            @CursorMovesTwo.canceled -= instance.OnCursorMovesTwo;
        }

        public void RemoveCallbacks(IThePlayerActions instance)
        {
            if (m_Wrapper.m_ThePlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IThePlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_ThePlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ThePlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ThePlayerActions @thePlayer => new ThePlayerActions(this);
    private int m_ExternalControllerSchemeIndex = -1;
    public InputControlScheme ExternalControllerScheme
    {
        get
        {
            if (m_ExternalControllerSchemeIndex == -1) m_ExternalControllerSchemeIndex = asset.FindControlSchemeIndex("ExternalController");
            return asset.controlSchemes[m_ExternalControllerSchemeIndex];
        }
    }
    private int m_MouseControllerSchemeIndex = -1;
    public InputControlScheme MouseControllerScheme
    {
        get
        {
            if (m_MouseControllerSchemeIndex == -1) m_MouseControllerSchemeIndex = asset.FindControlSchemeIndex("MouseController");
            return asset.controlSchemes[m_MouseControllerSchemeIndex];
        }
    }
    public interface IThePlayerActions
    {
        void OnCursorMoves(InputAction.CallbackContext context);
        void OnLeftAbilitySwitch(InputAction.CallbackContext context);
        void OnRightAbilitySwitch(InputAction.CallbackContext context);
        void OnCursorMovesTwo(InputAction.CallbackContext context);
    }
}
