//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Inputs/thePlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ThePlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ThePlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""thePlayerControls"",
    ""maps"": [
        {
            ""name"": ""CursorMoveAround"",
            ""id"": ""3d0a8e6b-8566-4f16-9fa4-ef81b127f9c1"",
            ""actions"": [
                {
                    ""name"": ""CursorMoves"",
                    ""type"": ""Value"",
                    ""id"": ""202045b3-6e55-4dfb-9bfe-f226924b11dc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cf533021-3873-4fb1-8a35-e8b019b08b15"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorMoves"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CursorMoveAround
        m_CursorMoveAround = asset.FindActionMap("CursorMoveAround", throwIfNotFound: true);
        m_CursorMoveAround_CursorMoves = m_CursorMoveAround.FindAction("CursorMoves", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CursorMoveAround
    private readonly InputActionMap m_CursorMoveAround;
    private List<ICursorMoveAroundActions> m_CursorMoveAroundActionsCallbackInterfaces = new List<ICursorMoveAroundActions>();
    private readonly InputAction m_CursorMoveAround_CursorMoves;
    public struct CursorMoveAroundActions
    {
        private @ThePlayerControls m_Wrapper;
        public CursorMoveAroundActions(@ThePlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CursorMoves => m_Wrapper.m_CursorMoveAround_CursorMoves;
        public InputActionMap Get() { return m_Wrapper.m_CursorMoveAround; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CursorMoveAroundActions set) { return set.Get(); }
        public void AddCallbacks(ICursorMoveAroundActions instance)
        {
            if (instance == null || m_Wrapper.m_CursorMoveAroundActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CursorMoveAroundActionsCallbackInterfaces.Add(instance);
            @CursorMoves.started += instance.OnCursorMoves;
            @CursorMoves.performed += instance.OnCursorMoves;
            @CursorMoves.canceled += instance.OnCursorMoves;
        }

        private void UnregisterCallbacks(ICursorMoveAroundActions instance)
        {
            @CursorMoves.started -= instance.OnCursorMoves;
            @CursorMoves.performed -= instance.OnCursorMoves;
            @CursorMoves.canceled -= instance.OnCursorMoves;
        }

        public void RemoveCallbacks(ICursorMoveAroundActions instance)
        {
            if (m_Wrapper.m_CursorMoveAroundActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICursorMoveAroundActions instance)
        {
            foreach (var item in m_Wrapper.m_CursorMoveAroundActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CursorMoveAroundActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CursorMoveAroundActions @CursorMoveAround => new CursorMoveAroundActions(this);
    public interface ICursorMoveAroundActions
    {
        void OnCursorMoves(InputAction.CallbackContext context);
    }
}
